### ISSUE TITLE
CTAN archive directory structure

### ISSUE THREAD

**Issue by phst** [phst/lualatex-math#10]
From Petra:

```
 2. The contents of your zip file should be structured in
    the following way:
            lualatex-math.tds.zip
            lualatex-math/
                 MANIFEST
                 Makefile
                 README
                 ... etc. ...
    that is: all the files except for the .tds.zip included
    in a directory named lualatex-math/ and the .tds.zip
    in parallel to that directory.
    (Please do not reupload because of that!  This is a
     general remark intended for the next time you happen
     to upload something.)

 3. I see lualatex-math.dtx and lualatex-math.ins as well as
    lualatex-math.sty.  I suppose that lualatex-math.sty can
    be generated from the .dtx and the .ins.  In that case I
    will have to delete it, because we do not want to hold
    any derived files except for the .pdfs.
    Please tell me which other files can be generated from
    the .dtx, so that I can remove them, too.
```

**Comment by josephwright** [comment]
The `l3build` script I added when I did an 'emergency release' covers all of this. I won't close the question or remove the Make-based scripts (not my project!) but that would be my suggestion: `l3build` is meant specifically for LaTeX code going to CTAN and 'just works'.

**Comment by phst** [comment]
I remember that I've encountered some minor discrepancy, which I need to check. Otherwise I'm happy to remove the makefile.

**Comment by phst** [comment]
One thing I just found was that `build.lua check` doesn't seem to run the unit test, at least it exits immediately without printing or doing anything.

**Comment by josephwright** [comment]
That's to be expected here: `l3build` is designed to run a particular form of testing set up, which doesn't match up with the ones that are built-in to `lualatex-math.dtx`. So when you try `build.lua check` it doesn't find any test files to look at.

**Comment by josephwright** [comment]
What I'll do is set up some `l3build` tests using the ones you've written: would be a good idea to have them available.

**Comment by phst** [comment]
Thanks. I'm currently working on integrating the comments into the new `.lvt` files, and I saw that `FALSE` appears several times in `amsmath.tlg`. Shouldn't all lines be `TRUE` if the test succeeds?

Also, is there be a way to improve the commentary in the `.tlg` files so that it's clear which line belongs to which assertion? (Splitting each assertion between two files means there should be some way to reunite the parts.)

**Comment by josephwright** [comment]
The usual approach in the team is to use `\TRUE \ERROR` or `\ERROR \FALSE` depending on the expected outcome of a test, rather than `\TRUE \FALSE` in all cases.

In terms of additional commentary, you could use the `\TEST` macro as we do in the LaTeX3 tests or simply add `\wlog` between tests. We tend to go for long-ish blocks in the team and simply count up the number of outcomes expected :-)
