### ISSUE TITLE
Release 1.5 did not update the datestamp of the package, only version number

### ISSUE THREAD

**Issue by jfbu** [phst/lualatex-math#18]
In `lualatex-math.sty`:

    \ProvidesExplPackage{lualatex-math}{2015/09/22}{1.5}%

but the announcement on CTAN had

    Version number: 1.5 2016-03-13

As LaTeX provides a mechanism using the release date this complicates a bit checking at runtime from inside a package which version of `lualatex-math` is available.

**Comment by jfbu** [comment]
I had a doubt about having made noise for nothing but `2015/09/22` really is the date of previous release `1.4a`.

**Comment by phst** [comment]
Sorry, that was an oversight. The date in 1.6 should now again be correct.
