### ISSUE TITLE
Compatibility with amsmath is broken

### ISSUE THREAD

**Issue by tweh** [phst/lualatex-math#20]
Due to some changes in the implementation of `\genfrac` in `amsmath` the compatibility is broken and in (de)nominators `\mathstyle` doesn’t give the right/expected result. Please see [_Value of LuaTeX’s \mathstyle in \frac (de)nominator_ on TeX.SX](https://tex.stackexchange.com/q/371134/4918) for further details.

```tex
% !TeX program = lualatex
\documentclass{article}

\usepackage{amsmath}
\usepackage{lualatex-math}

\begin{document}
   $\dfrac{\mathstyle}{\mathstyle} \neq \dfrac{4}{5}$
\end{document}
```

Pleas note that `\frac` still works, as it is not defined using `\genfrac`.

**Comment by phst** [comment]
Thanks for the report, and sorry for the slow response. I've adapted the patch; could you maybe check whether it works now for your use case?

**Comment by davidcarlisle** [comment]
sorry about that I should have checked and flagged that with you at the
time:-)

**Comment by tweh** [comment]
Hi, seems to work now in the version I downloaded from the current master branch (`\filelist` → `2017/06/15 v1.7`). For sake of completeness the CTAN version (`\filelist` → `2016/04/16 v1.6`) does not work.

**Comment by phst** [comment]
Thanks, I've uploaded the new version to CTAN.
