### ISSUE TITLE
More Warnings

### ISSUE THREAD

**Issue by PlayfulPan** [phst/lualatex-math#23]
Hello,

LuaLaTeX math gives the following warning when used with the mathtools package.

> Package lualatex-math Warning: I've expected \MT_cramped_internal:Nn to have
> (lualatex-math)                the meaning
> (lualatex-math)                macro:#1#2->\sbox \z@ {$\m@th
> (lualatex-math)                #1\nulldelimiterspace =\z@ \radical \z@
> (lualatex-math)                {#2}$}\ifx #1\displaystyle \dimen@ =\fontdimen
> (lualatex-math)                8\textfont 3\advance \dimen@ .25\fontdimen
> (lualatex-math)                5\textfont 2\else \dimen@ =1.25\fontdimen 8\ifx
> (lualatex-math)                #1\textstyle \textfont \else \ifx
> (lualatex-math)                #1\scriptstyle \scriptfont \else
> (lualatex-math)                \scriptscriptfont \fi \fi 3\fi \advance \dimen@
> (lualatex-math)                -\ht \z@ \ht \z@ =-\dimen@ \box \z@ ,
> (lualatex-math)                but it has the meaning
> (lualatex-math)                macro:#1#2->{\ensuremath {\use:c
> (lualatex-math)                {cramped\cs_to_str:N #1}#2}}.
> 
> )

It appears that mathtools incorporates the patch LuaLaTeX-math is trying to perform, so I think it is safe to simply remove the patch being applied to  \MT_cramped_internal:Nn from lualatex-math. 

It's just a warning and it doesn't really affect anything, but it is a bit annoying and the fix appears to be pretty easy.

**Comment by PlayfulPan** [comment]
Actually, it appears that this issue is fixed in version 1.10, so sorry for the false alarm.

I would request however that you update the package on CTAN if not too much effort since that is still version 1.9. 

Thanks!

**Comment by phst** [comment]
Hmm, I thought I had already done that, but apparently not. Should be done now.

**Comment by phst** [comment]
Do you still see these warnings with version 1.11?

**Comment by qoheniac** [comment]
With version 1.11 I don't see this Warning anymore.

**Comment by phst** [comment]
OK, I'm closing this issue then.
