### ISSUE TITLE
LaTeX hooks warnings

### ISSUE THREAD

**Issue by xsrvmy** [phst/lualatex-math#24]
When using `unicode-math`, this package produces multiple warnings like this:
```
LaTeX hooks Warning: Generic hook 'package/before/amsmath' is deprecated.
(hooks)              Use hook 'package/amsmath/before' instead.
```

Also reported here:
https://github.com/wspr/unicode-math/issues/574

**Comment by phst** [comment]
Thanks for the report. This has been fixed with version 1.12, which I've just uploaded to CTAN.
