### ISSUE TITLE
The 16 math families limit in LaTeX kernel should be kept

### ISSUE THREAD

**Issue by khaledhosny** [phst/lualatex-math#7]
Though LuaTeX allows for 256 math families, the syntax of old math primitives (`\mathcode`, `\mathchar`, etc.) does not allow for more than 16 families thus increasing the limit set in LaTeX kernel will just cause unexpected behavior when more than 16 families are used with legacy math packages (extended math primitives can use more families but there you actually don’t need that many, thanks to Unicode and OpenType requiring less number of fonts).

Actually the patch in `lualatex-math` does not work and the limits is still there, so I suggest just dropping the patch.

```latex
\documentclass{article}
\usepackage{lualatex-math}

\DeclareSymbolFont{testa}{U}{txmia}{m}{it}
\DeclareSymbolFont{testb}{U}{txmia}{m}{it}
\DeclareSymbolFont{testc}{U}{txmia}{m}{it}
\DeclareSymbolFont{testd}{U}{txmia}{m}{it}
\DeclareSymbolFont{teste}{U}{txmia}{m}{it}
\DeclareSymbolFont{testf}{U}{txmia}{m}{it}
\DeclareSymbolFont{testg}{U}{txmia}{m}{it}

\DeclareSymbolFont{lettersA}{U}{txmia}{m}{it}

\usepackage{amsfonts}
\usepackage{MnSymbol}

\begin{document}
\[\mathtt{Test} \mathcal{L} * - ><\]
\end{document}
```

**Comment by davidcarlisle** [comment]
Just changing \newmathgroup to 256 without changing \DeclareMathSymbol and friends isn't safe but \DeclareMathAlphabet is OK, the code I suggest at

http://tex.stackexchange.com/a/232620/1090

allows the extended range for math alphabets but restricts \DeclareSymbolFont to 16 

I suspect it would be too intrusive for the format by default to use \U... but a package could add extended versions, say  \UDeclareSymbolFont , \UDeclareMathSymbol etc that did go past 16 and
use \U.... versions of the math primitives.


Note that the extended allocation (and possibly the extension of `\DeclareMathAlphabet`) are planned for inclusion in latex 2015 which will include engine-aware allocation for all register types in the format, so the redefinition of `\new@mathgroup/\newfam` needs to be conditional on it being an "old" format wrapping it in `\ifx\e@alloc\@undefined ... \f`i would be enough.

The 2015 latex release is on public test currently as advertised on latex-l.

**Comment by josephwright** [comment]
I suggest that `lualatex-math` checks for the kernel update and if present does nothing. With older kernels it can use the same code as @davidcarlisle has suggested for a kernel addition, so extending the bit that works but not the bit that doesn't. If someone wants to then do the `\U...` bit (might I guess be me) that will apply to both XeTeX and LuaTeX so should be separate anyway.

**Comment by phst** [comment]
If the new kernel will support all available families in LuaTeX out of the box, I'd prefer to drop the patch unconditionally rather than trying to support multiple kernels. Given that the patch itself doesn't work reliably and that user who update lualatex-math should hopefully also update LaTeX itself, that looks like a better way forward.

**Comment by josephwright** [comment]
The kernel update will appear in TL2015 and is on CTAN now (for the TL2015 pretest).
